import { Inter } from 'next/font/google'
import './globals.css'
import Header from '../components/header/Header'
import SideBar from '../components/header/SideBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: `Developer Mike`,
  description: 'Generated by create next app',
  manifest: '/manifest.json',
  icons: {
    apple: '/icon.png',
  },
  themeColor: '#000000',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SideBar />
        {children}
      </body>
    </html>
  )
}
